### ISSUE TITLE
jekyll-feed

### ISSUE THREAD

**Issue by akhyarrh** [benbalter/jekyll-seo-tag#23]
I don't know how to give better title.

### `jekyll-feed` use `site.name:`, not `site.title:`
```yaml
# Should I use this ?
# Look funny ;)
title:     'Jekyll'
name: 'Jekyll'
```

### Author
```yaml
# post front-matter

# jekyll-seo-tag
author: John Doe

# jekyll-feed
author:
  name: John Doe
  uri: john-doe.com
```

Will there be a conflict?
